# Blog info
blog_name: bukas
slogan: stay hungry, stay foolish.

# For seo
keywords: bukas,前端,设计,Hexo主题,前端开发,用户体验,frontend,design,nodejs,JavaScript,es6

# Stats
# Analytics
google_analytics:
    id: UA-49034721-1
    site: w3cboy.com
# baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

favicon:

# social
# disqus_shortname: bukas
duoshuo_shortname: yhzblog

show_count: true

init_page_content: HOME_NAV  # HOME_NAV | POST

home_nav:
  - name: Blog
    url: /archives/
  - name: Github
    url: https://github.com/huanz
    target: _blank
  - name: Weibo
    url: http://weibo.com/u/2335228667/
    target: _blank

# config page nav (盒子)
page_nav:
  - 首页: /
  - 博客: /archives/
  - 标签: /tags/
  - 关于: /about/
  - RSS: /w3cboy.xml

post:
  header_align: center # left|center

link:
  - name: 织网
    info: 身体和灵魂，总有一个在路上
    url: http://zheng-ji.info/
    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=460
  - name: Dongyado
    info: 生命不止，折腾不息
    url: http://dongyado.com/
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=460
  - name: OrangeCoder
    info: xxx
    url: http://orangecoder.com/
    avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=460
  - name: EverET
    info: xxx
    url: http://everet.org/about-me/
    avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=460
  - name: 题叶
    info: xxx
    url: http://tiye.me/
    avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=460


about:
  - type: me
    icon: icon-user
    text_value:
    - "CCNU，1991，Winter."
    - "喜欢编程，爱睡懒觉."
    - "前端开发工程师，常用 HTML / CSS / JavaScript."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@huanz"
    text_value_url: https://github.com/huanz
  - type: weibo
    text_key: 微博
    text_value: "@_bukas"
    text_value_url: http://weibo.com/u/2335228667
  - type: mail
    text_key: Gmail
    text_value: "yhz1219@gmail.com"
  - type: location
    icon: icon-location
    text_value: 北京
